Repository openshift/doozer, pull requests merged in 2018-11, with the labels that each got.

#1 Updated console sources automation
  tools/bin/update-yarn-npm-sources
  tools/src/ocp_cd_tools/distgit.py
  tools/src/ocp_cd_tools/exectools.py
  tools/src/ocp_cd_tools/schema_image.yml
Labels: lgtm, size/L

#2 Making doozer installable
  .gitignore
  MANIFEST.in
  README.md
  doozer
  doozer.py
  doozerlib/__init__.py
  doozerlib/assertion.py
  doozerlib/assertion_test.py
  doozerlib/brew.py
  doozerlib/brew_test.py
  doozerlib/bugzilla.py
  doozerlib/bugzilla_test.py
  doozerlib/cli_opts.py
  doozerlib/config.py
  doozerlib/constants.py
  doozerlib/container.py
  doozerlib/container_test.py
  doozerlib/distgit.py
  doozerlib/distgit_test.py
  doozerlib/errata.py
  doozerlib/errata_test.py
  doozerlib/exceptions.py
  doozerlib/exectools.py
  doozerlib/exectools_test.py
  doozerlib/image.py
  doozerlib/image_test.py
  doozerlib/logutil.py
  doozerlib/metadata.py
  doozerlib/metadata_test.py
  doozerlib/model.py
  doozerlib/pushd.py
  doozerlib/pushd_test.py
  doozerlib/repos.py
  doozerlib/rpmcfg.py
  doozerlib/rpmcfg_test.py
  doozerlib/runtime.py
  doozerlib/runtime_test.py
  doozerlib/schema_group.yml
  doozerlib/schema_image.yml
  doozerlib/schema_rpm.yml
  doozerlib/test_structures.py
  doozerlib/util.py
  hack/util/rpm_print/rpm_print.sh
  requirements.txt
  setup.py
  tools/.gitignore
  tools/HACKING.md
  tools/MANIFEST.in
  tools/bin/elliott
  tools/bin/oit
  tools/doc/elliott.md
  tools/hack/cert-chain.crt
  tools/hack/env_setup.sh
  tools/setup.py
  tools/src/prepare_repos.py
  tools/util/__init__.py
  tools/util/colorprint.py
  tools/util/ose_conf_load.sh
  tools/util/record_report.py
Labels: size/XXL

#3 Add a unique nonce to yum repoids
  doozerlib/repos.py
Labels: size/XS

#4 Write images:print results to a file if provided
  doozer
  doozerlib/runtime.py
Labels: lgtm, size/S

#5 prevent distgit hanging on git push --tags
  doozerlib/distgit.py
Labels: size/XS

#6 Integrating gitdata and misc fixes
  doozer
  doozerlib/cli_opts.py
  doozerlib/config.py
  doozerlib/image.py
  doozerlib/metadata.py
  doozerlib/rpmcfg.py
  doozerlib/runtime.py
  doozerlib/util.py
  requirements.txt
Labels: lgtm, size/L

#9 Fix stream load
  doozerlib/runtime.py
Labels: size/XS
