Repository openshift/doozer, pull requests merged in 2019-04, with the labels that each got.

#71 Updating docs
  Container.md
  Installation.md
  README.md
  Usage.md
Labels: size/L

#74 Fix dry_run
  doozerlib/distgit.py
Labels: size/M

#73 rpmcfg.py: enable pushing release commit to origin
  doozerlib/rpmcfg.py
  doozerlib/schema_rpm.yml
Labels: lgtm, size/L

#75 Add yum clean all before reposync
  doozer
Labels: lgtm, size/XS

#69 ART-514: print out tags in necessary RPM builds for 4.1
  doozer
  doozerlib/distgit.py
  doozerlib/distgit_test.py
  doozerlib/runtime.py
Labels: size/M

#77 rpmcfg: use tito tag or doozer tag, not both
  doozerlib/rpmcfg.py
Labels: size/S

#79 distgit.py: search builds for component not dg name
  doozerlib/distgit.py
  doozerlib/distgit_test.py
Labels: lgtm, size/S

#80 distgit.py: fix source_alias in dockerfile_notify
  doozerlib/distgit.py
Labels: lgtm, size/M

#78 add config:gen-csv new subcommand to dump csv file
  .gitignore
  doozer
  doozerlib/config.py
Labels: lgtm, size/M

#82 enable configuring container.yaml contents
  doozerlib/distgit.py
  doozerlib/schema_image.yml
Labels: lgtm, size/XS

#81 Adding Cluster Service Version processing
  doozerlib/distgit.py
  doozerlib/image.py
  doozerlib/runtime.py
  doozerlib/schema_image.yml
Labels: lgtm, size/L

#83 distgit.py: work around OSBS bug
  doozerlib/distgit.py
Labels: lgtm, size/S
