Repository openshift/doozer, pull requests merged in 2019-03, with the labels that each got.

#41 Adding dist-git-ignore option
  doozerlib/distgit.py
  doozerlib/schema_group.yml
  doozerlib/schema_image.yml
Labels: lgtm, size/S

#43 add config:print --yaml
  doozer
  doozerlib/config.py
Labels: size/M

#42 distgit: add timeout to rhpkg push, etc
  doozerlib/distgit.py
Labels: size/XS

#44 distgit: extract container build logs from brew logs
  doozerlib/distgit.py
Labels: size/M

#45 distgit: container-build-logs for failed builds
  doozerlib/distgit.py
Labels: lgtm, size/XS

#46 fix typo add add idea gitignore
  .gitignore
  README.md
Labels: size/XS

#47 adding back pre_step
  doozer
Labels: lgtm, size/XS

#48 Fixing push state messages
  doozer
  doozerlib/distgit.py
  doozerlib/state.py
Labels: lgtm, size/M

#49 Always delete .gitignore for distgits
  doozerlib/distgit.py
Labels: size/XS

#53 Fixing for latest version of pyyaml
  doozerlib/distgit.py
  doozerlib/runtime.py
Labels: size/XS

#55 rpmcfg.py: roll back the temporary commit when done
  doozerlib/rpmcfg.py
Labels: size/S

#54 distgit.py: clone with the branch to begin with
  doozerlib/distgit.py
Labels: lgtm, size/S

#59 distgit.py: make scan-sources work with aliases
  doozerlib/distgit.py
Labels: size/XS

#58 runtime and schema: group option to ignore source branch fallbacks
  doozerlib/runtime.py
  doozerlib/schema_group.yml
Labels: size/S

#61 Do not include non-release images in release sync
  doozer
Labels: size/XS

#62 Doozer bump
  doozerlib/VERSION
Labels: size/XS

#63 Only do travis deploy from openshift/doozer
  .travis.yml
Labels: lgtm, size/XS

#60 Adding global options to settings.yaml
  Usage.md
  doozer
  doozerlib/cli_opts.py
  doozerlib/distgit.py
  doozerlib/runtime.py
Labels: lgtm, size/M

#51 Containerize Doozer
  Container.md
  Dockerfile
  build_doozer
  certs/RH-IT-Root-CA.crt
  container_install.sh
  doozer
  doozerlib/config.py
  doozerlib/container.py
  doozerlib/container_test.py
  doozerlib/distgit.py
  doozerlib/image.py
  entrypoint.sh
  push_doozer
  requirements.txt
  rundoozer.sh
  rundoozer/rundoozer
  rundoozer/setup.py
Labels: size/XXL

#65 fix for non_release images
  doozer
  doozerlib/runtime.py
Labels: lgtm, size/S

#66 important fixes for broken stuff
  doozerlib/image.py
  doozerlib/repos.py
  doozerlib/runtime.py
Labels: lgtm, size/XS

#68 Adding config:read-group
  doozer
  doozerlib/runtime.py
  doozerlib/util.py
Labels: lgtm, size/M

#70 Adding settings path and container_opts
  rundoozer/rundoozer
  rundoozer/setup.py
Labels: lgtm, size/S

#72 add shiywang to doozer approvers/reviewers
  OWNERS
Labels: size/XS
