Repository openshift/doozer, pull requests merged in 2019-02, with the labels that each got.

#30 Adding install script
  Installation.md
  Usage.md
  install.sh
Labels: size/L

#31 Adding reposync command
  doozer
  doozerlib/repos.py
Labels: lgtm, size/L

#33 Fixing image error name bug
  doozer
  doozerlib/distgit.py
  doozerlib/rpmcfg.py
Labels: lgtm, size/S

#34 fix release bump
  doozerlib/distgit.py
Labels: lgtm, size/S

#35 images:print: Add ability to print specific label from Dockerfile
  doozer
Labels: lgtm, size/XS

#32 Adding stateful logic
  doozer
  doozerlib/config.py
  doozerlib/distgit.py
  doozerlib/image.py
  doozerlib/metadata.py
  doozerlib/runtime.py
  doozerlib/state.py
Labels: lgtm, size/L

#36 exectools.cmd_gather should not busy-wait on output
  doozerlib/exectools.py
Labels: lgtm, size/XS

#37 Adding @tbielawa oc tweak for image push
  doozer
  doozerlib/distgit.py
  doozerlib/schema_group.yml
Labels: lgtm, size/M

#38 Fixing state save
  doozerlib/runtime.py
Labels: size/XS

#40 A few push fixes
  doozer
  doozerlib/distgit.py
Labels: lgtm, size/M
