Repository openshift/doozer, pull requests merged in 2019-12, with the labels that each got.

#150 Allow reposync to be disabled by repo
  doozerlib/cli/__main__.py
  doozerlib/repos.py
  doozerlib/schema_group.yml
Labels: size/S

#154 make dotconfig respect unicode templates
  doozerlib/dotconfig.py
Labels: lgtm, size/XS

#149 Update dev container configuration
  .devcontainer/dev.Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/krb5-redhat.conf
  requirements-dev.txt
Labels: lgtm, size/M

#155 License dotconfig and gitdata under LGPL v3
  README.md
  doozerlib/dotconfig.py
  doozerlib/gitdata.py
Labels: lgtm, size/S

#156 Add use_source_version option for cpaas users
  doozerlib/distgit.py
  doozerlib/schema_image.yml
Labels: size/XS
