Repository openshift/doozer, pull requests merged in 2019-11, with the labels that each got.

#133 Adding brew_tag option
  doozer
  doozerlib/image.py
  doozerlib/metadata.py
  doozerlib/operator_metadata.py
  doozerlib/runtime.py
  tests/test_operator_metadata.py
Labels: lgtm, size/M

#136 Output stack traces on rebase errors
  doozer
  doozerlib/distgit.py
Labels: lgtm, size/XS

#134 Embed pygitdata for future refactoring and Python 3 migration
  doozerlib/gitdata.py
  doozerlib/runtime.py
  requirements.txt
Labels: lgtm, size/L

#137 Fix build-sync adding non-manifest lists in multiarch mode
  doozerlib/VERSION
  doozerlib/cli/__main__.py
Labels: lgtm, size/XS

#141 Fix doozerlib.cli is not included in setup.py
  doozerlib/VERSION
  setup.py
Labels: size/XS

#142 [ART-1245] runtime: leave brew_tag None by default
  doozerlib/runtime.py
Labels: lgtm, size/XS

#143 Allow images missing for different arches
  doozerlib/VERSION
  doozerlib/cli/__main__.py
Labels: lgtm, size/L

#146 Fix operator metadata lookups [ART-1238] [ART-1175]
  doozerlib/operator_metadata.py
  tests/test_operator_metadata.py
Labels: lgtm, size/M

#147 Provide for arch specific release controllers
  doozerlib/VERSION
  doozerlib/cli/__main__.py
Labels: lgtm, size/XS
