Repository openshift/doozer, pull requests merged in 2019-01, with the labels that each got.

#20 Only add images that exist, sorted the ImageStream
  doozer
Labels: size/S

#19 distgit: cleaner yum mangling
  doozerlib/distgit.py
  doozerlib/distgit_test.py
Labels: size/L

#21 sync-gen: Print skipped image lists after generation
  doozer
Labels: size/S

#24 changing source labels
  doozerlib/distgit.py
Labels: lgtm

#18 [WIP] Adding local builds
  README.md
  doozer
  doozerlib/__init__.py
  doozerlib/brew.py
  doozerlib/brew_test.py
  doozerlib/bugzilla.py
  doozerlib/bugzilla_test.py
  doozerlib/constants.py
  doozerlib/container.py
  doozerlib/distgit.py
  doozerlib/errata.py
  doozerlib/errata_test.py
  doozerlib/exectools.py
  doozerlib/image.py
  doozerlib/metadata.py
  doozerlib/rpmcfg.py
  doozerlib/rpmcfg_test.py
  doozerlib/runtime.py
  doozerlib/test_structures.py
  doozerlib/util.py
Labels: do-not-merge/work-in-progress, size/XXL

#27 Clone sources at depth 1
  doozerlib/runtime.py
Labels: size/M
