Repository openshift/doozer, pull requests merged in 2019-05, with the labels that each got.

#85 Revert "distgit.py: work around OSBS bug"
  doozerlib/distgit.py
Labels: size/S

#88 Fixing CSV replace
  doozerlib/VERSION
  doozerlib/distgit.py
Labels: size/XS

#86 Adding new CSV namespace option
  doozerlib/distgit.py
  doozerlib/schema_group.yml
Labels: lgtm, size/S

#87 Check build_lock before releasing
  doozerlib/distgit.py
Labels: lgtm, size/XS

#92 Fix doozer build lock failure
  doozerlib/VERSION
  doozerlib/distgit.py
Labels: size/XS

#91 fixing os.mkdir race-condition in push_image
  doozerlib/distgit.py
Labels: lgtm, size/S

#93 Forcing REQUESTS_CA_BUNDLE env var
  doozer
Labels: lgtm, size/XS

#94 distgit: add envvars to relay source metadata
  doozerlib/distgit.py
Labels: lgtm, size/S

#95 distgit: add SOURCE_DATE_EPOCH env var
  doozerlib/distgit.py
Labels: lgtm, size/XS

#98 refer to metadata by distgit_key instead of name
  doozerlib/distgit.py
  doozerlib/state.py
Labels: size/M

#100 List "koji" on requirements.txt
  requirements.txt
Labels: size/XS

#101 [ART-546] tox config to run flake8 + unit tests
  .gitignore
  requirements-test.txt
  tox.ini
Labels: lgtm, size/S

#102 Make flake8 happy ;D
  doozerlib/assertion.py
  doozerlib/brew.py
  doozerlib/distgit.py
  doozerlib/distgit_test.py
  doozerlib/exectools.py
  doozerlib/image_test.py
  doozerlib/metadata.py
  doozerlib/metadata_test.py
  doozerlib/model.py
  doozerlib/rpmcfg.py
  doozerlib/rpmcfg_test.py
  doozerlib/runtime.py
  doozerlib/runtime_test.py
Labels: lgtm, size/M

#104 Run `tox` on Travis
  .ci/Dockerfile
  .travis.yml
Labels: lgtm, size/S

#105 Move unit tests outside doozerlib module
  tests/assertion_test.py
  tests/distgit_test.py
  tests/exectools_test.py
  tests/image_test.py
  tests/metadata_test.py
  tests/pushd_test.py
  tests/rpmcfg_test.py
  tests/runtime_test.py
  tox.ini
Labels: size/XS
