Repository openshift/doozer, pull requests merged in 2019-10, with the labels that each got.

#117 ART-948: Support specifying out-of-tree sources in ocp-build-data.
  doozerlib/distgit.py
  doozerlib/rpmcfg.py
  doozerlib/source_modifications.py
  doozerlib/util.py
  requirements-dev.txt
  requirements.txt
  tests/test_source_modifications.py
Labels: size/L

#122 Explicitly only push amd64 to registry.reg-aws
  doozerlib/VERSION
  doozerlib/distgit.py
  tests/test_distgit/test_image_distgit/test_push_image.py
Labels: lgtm, size/XS

#121 Allow group.yml to disable builds
  doozer
  doozerlib/runtime.py
  doozerlib/schema_group.yml
Labels: size/L

#125 Adding --rhpkg-config option
  doozer
  doozerlib/cli_opts.py
  doozerlib/distgit.py
  doozerlib/operator_metadata.py
  doozerlib/runtime.py
  tests/test_distgit/test_generic_distgit.py
  tests/test_operator_metadata.py
  tests/test_runtime.py
Labels: lgtm, size/M

#118 ART-1113: refactor modification actions
  doozerlib/distgit.py
  doozerlib/rpmcfg.py
  doozerlib/source_modifications.py
Labels: lgtm, size/L

#126 Simplify repo reset logic
  doozerlib/rpmcfg.py
Labels: lgtm, size/S

#123 [ART-1005] operator-metadata: work with NVR
  doozer
  doozerlib/brew.py
  doozerlib/operator_metadata.py
  tests/test_distgit/test_build_image_ref_name.py
  tests/test_distgit/test_convert_source_url_to_https.py
  tests/test_distgit/test_image_distgit/test_push_image.py
  tests/test_distgit/test_pull_image.py
  tests/test_distgit/test_recursive_overwrite.py
  tests/test_operator_metadata.py
Labels: lgtm, size/L

#120 Always pull latest CI image
  Jenkinsfile
Labels: lgtm, size/XS

#129 Allow doozer to filter multiple spec files
  doozerlib/rpmcfg.py
Labels: size/XS

#131 Use full paths when comparing; avoid reliance on cwd
  doozerlib/rpmcfg.py
Labels: size/XS

#127 Embed pydotconfig into doozer
  doozer
  doozerlib/dotconfig.py
  requirements.txt
  rundoozer/rundoozer
  rundoozer/setup.py
Labels: size/L

#128 Python 3: Create python-3 branch for migration
  README.md
  tox.ini
Labels: size/XS
