Repository openshift/doozer, pull requests merged in 2020-03, with the labels that each got.

#192 [ART-1240] Clean out env vars in dist-git only Dockerfiles
  doozerlib/VERSION
  doozerlib/distgit.py
Labels: size/S

#193 Restore + to KUBE_GIT_MINOR
  doozerlib/VERSION
  doozerlib/distgit.py
  doozerlib/rpmcfg.py
Labels: size/XS

#194 images:list should skip disabled by default
  doozerlib/VERSION
  doozerlib/cli/__main__.py
Labels: size/S

#185 Inject team ownership info into rpms/images
  doozerlib/distgit.py
  doozerlib/gitdata.py
  doozerlib/metadata.py
  doozerlib/rpmcfg.py
  doozerlib/runtime.py
  tests/test_rpmcfg.py
Labels: size/L
