Repository openshift/doozer, pull requests merged in 2020-01, with the labels that each got.

#163 Fix UnicodeDecodeError when building 3.11 openshift-ansible RPM
  doozerlib/rpmcfg.py
Labels: lgtm, size/XS

#161 Add `--dry-run` option to images:build and rpms:build
  doozerlib/cli/__main__.py
  doozerlib/distgit.py
  doozerlib/rpmcfg.py
Labels: lgtm, size/M

#144 Merge multi & single arch gen-payload
  doozerlib/cli/__main__.py
Labels: lgtm, size/L

#164 CSV with unicode chars raise exceptions
  doozerlib/distgit.py
Labels: lgtm, size/S

#167 [ART-1451] Use UTF-8 in operator_metadata file operations
  doozerlib/operator_metadata.py
Labels: size/S

#168 Tolerate when tito init does not make commit
  doozerlib/rpmcfg.py
  doozerlib/runtime.py
Labels: lgtm, size/S

#169 Bug 1792142: Correct CSV "relatedImages" format
  doozerlib/operator_metadata.py
  tests/test_operator_metadata.py
Labels: bugzilla/invalid-bug, lgtm, size/S

#165 fix broken tag_exists
  doozerlib/metadata.py
  tests/test_metadata.py
Labels: size/M

#158 ART-128: Support ODCS composes for OSBS builds
  .devcontainer/dev.Dockerfile
  .devcontainer/settings.yaml
  doozerlib/brew.py
  doozerlib/cli/__main__.py
  doozerlib/distgit.py
  doozerlib/image.py
  doozerlib/repos.py
Labels: size/L

#160 Add functional tests
  .devcontainer/dev.Dockerfile
  functional_tests/README.md
  functional_tests/__init__.py
  functional_tests/test_cleanup.py
  functional_tests/test_config.py
  functional_tests/test_images.py
  functional_tests/test_operator_metadata.py
  functional_tests/test_release.py
  functional_tests/test_rpms.py
  requirements-dev.txt
  setup.py
  tox.ini
Labels: size/XL

#159 Fully migrate to Python 3 and cleanup some dead code
  .devcontainer/dev.Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yaml
  Installation.md
  README.md
  doozer
  doozerlib/VERSION
  doozerlib/__init__.py
  doozerlib/assertion.py
  doozerlib/brew.py
  doozerlib/cli/__main__.py
  doozerlib/cli/cli_opts.py
  doozerlib/config.py
  doozerlib/distgit.py
  doozerlib/dotconfig.py
  doozerlib/exceptions.py
  doozerlib/exectools.py
  doozerlib/gitdata.py
  doozerlib/image.py
  doozerlib/logutil.py
  doozerlib/metadata.py
  doozerlib/model.py
  doozerlib/operator_metadata.py
  doozerlib/pushd.py
  doozerlib/repos.py
  doozerlib/rpmcfg.py
  doozerlib/runtime.py
  doozerlib/schema_group.yml
  doozerlib/schema_image.yml
  doozerlib/schema_rpm.yml
  doozerlib/source_modifications.py
  doozerlib/state.py
  doozerlib/util.py
  external_files.py
  requirements.txt
  rundoozer/rundoozer
  rundoozer/setup.py
  setup.py
  tests/test_assertion.py
  tests/test_distgit/support.py
  tests/test_distgit/test_build_image_ref_name.py
  tests/test_distgit/test_convert_source_url_to_https.py
  tests/test_distgit/test_generic_distgit.py
  tests/test_distgit/test_image_distgit/test_image_distgit.py
  tests/test_distgit/test_image_distgit/test_push_image.py
  tests/test_distgit/test_pull_image.py
  tests/test_distgit/test_recursive_overwrite.py
  tests/test_distgit/test_rpm_distgit.py
  tests/test_exectools.py
  tests/test_image.py
  tests/test_metadata.py
  tests/test_operator_metadata.py
  tests/test_pushd.py
  tests/test_rpmcfg.py
  tests/test_runtime.py
  tests/test_source_modifications.py
  tox.ini
Labels: size/XXL

#170 Fix dev container build
  .devcontainer/dev.Dockerfile
Labels: size/XS
