Repository openshift/doozer, pull requests merged in 2020-02, with the labels that each got.

#172 Encoding/decoding handling
  doozerlib/cli/__main__.py
  doozerlib/exectools.py
  doozerlib/util.py
Labels: lgtm, size/M

#157 Improve command executions
  doozerlib/constants.py
  doozerlib/distgit.py
  doozerlib/gitdata.py
  doozerlib/runtime.py
  tests/test_distgit/test_generic_distgit.py
  tests/test_distgit/test_rpm_distgit.py
  tests/test_runtime.py
Labels: lgtm, size/M

#171 2020 01 30 add extra repo configs to group yml
  doozerlib/VERSION
  doozerlib/repos.py
  tests/test_repo.py
  tox.ini
Labels: lgtm, size/L

#173 Add more tests for repo class
  tests/test_repo.py
Labels: size/M

#176 Speed up images:print when dockerfile parsing is not required
  doozerlib/cli/__main__.py
Labels: size/M

#177 [ART-1513] Retry tag query with backoff
  doozerlib/metadata.py
  requirements.txt
  tests/test_metadata.py
Labels: lgtm, size/S

#175 metadata: ART-1520 handle 403 response
  doozerlib/metadata.py
Labels: lgtm, size/XS

#178 images:print: don't crash if no builds found for an image
  doozerlib/cli/__main__.py
Labels: lgtm, size/S

#181 [ART-1311] Drop Python2 support
  setup.py
  tox.ini
Labels: lgtm, size/XS

#183 Ignore .tito from source if we are not instructed to use it
  doozerlib/rpmcfg.py
Labels: size/S

#186 Inject OS_* variables expected by openshift builds
  doozerlib/cli/__main__.py
  doozerlib/distgit.py
  doozerlib/rpmcfg.py
Labels: size/M

#184 ART-1536: scan-sources should not count disabled images as changed
  doozerlib/cli/__main__.py
Labels: size/XS

#187 Add KUBE_ vars to spec
  doozerlib/VERSION
  doozerlib/rpmcfg.py
Labels: size/M

#188 Add OS_GIT_COMMIT to Dockerfile env
  doozerlib/distgit.py
Labels: size/XS

#182 Bring tag_exists check back
  doozerlib/distgit.py
Labels: size/XS

#189 Add KUBE_* to Dockerfiles when available
  doozerlib/distgit.py
Labels: size/M

#190 Prevent rpmcfg from creating non-origin commit
  doozerlib/rpmcfg.py
  doozerlib/runtime.py
Labels: size/L

#191 Simplify rpmcfg reset logic
  doozerlib/rpmcfg.py
Labels: size/M
